### ISSUE TITLE
Search bar in footer is showing meta information

### ISSUE THREAD

**Issue by skytland** [nasa/centerops.jsc.nasa.gov#1]
This is likely due to the additional code we wrote to pass STRAW review, but we need to fix it so it's not showing.

![screen shot 2015-10-27 at 11 19 59 am](https://cloud.githubusercontent.com/assets/168066/10764546/c5ecb204-7c9c-11e5-9848-8e18d041044f.png)

**Comment by MASTAD0N** [comment]
Fixed. Also, I have created a document that details the changes I have made to the various php files on the server in case they need to be altered again in the future.

**Comment by skytland** [comment]
Excellent, great idea.
