### ISSUE TITLE
Who to Contract page update

### ISSUE THREAD

**Issue by skytland** [nasa/centerops.jsc.nasa.gov#2]
The "Facility Management" pull down on the Who to Contract Site needs to updated. It only shows a portion of who to contact in FMOD.  My suggestion would be to replace it with a smart help tool where a person can type a brief description of their problem and the tool returns with the correct point of contact by looking for key words.  FMOD maintains database of job responsibilities that could be adapted for that purpose or we could simply provide the database and let the user look through it themselves for keywords then locate a point of contact.

![41de3839-ed1a-499b-943c-cfaab29ce5b0](https://cloud.githubusercontent.com/assets/168066/10769252/0ebb20c2-7cb3-11e5-90a6-f7e78c7ae344.png)

**Comment by skytland** [comment]
I think the "smart help tool" as described here is more a cognitive computing system that would require the ability to understand natural language.  We don't have the capability to build something like that ourselves and integrating with existing solutions might be expensive.  It's beyond the capability of the standard search included in the CMS as well.  It would require a database for the key contacts, which would likely require interfacing with NASA's existing systems (people.nasa.gov, etc).  It's going to be much simpler to restructure the page to make it easier to find the information.  I will reach back to the original requestor to discuss.

**Comment by jether123** [comment]
Understood on the difficulty with creating a help tool, just thought I would check. I will talk to JM about making the information more complete and easier to find.

Thank You

**Comment by skytland** [comment]
That sounds great.  I'll close the ticket for now, and soon as you have feedback from JM on a) what other information to include and b) any other ideas on how to structure it on the page to make it more accessible and readable, please let us know and we'll get right on it.
